name: conta_em_dia
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  injectable: ^2.7.1+4
  dartz: ^0.10.1
  dio: ^5.9.0
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  lucide_icons_flutter: ^3.1.9
  dropdown_button2: ^2.3.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  mocktail: ^1.0.4
  bloc_test: ^9.1.5
  injectable_generator: ^2.9.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/card/
    - assets/images/network/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
